# -*- coding: utf-8 -*-
"""ML_Lab_R_01_Linear_Reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-NguIUZvNnfRH2NxQqOI5Z0KW3YUzG7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("student-scores.csv")

df

df.plot(x='part_time_job', y='physics_score', style='o')
plt.title('part_time_job vs physics_score')
plt.xlabel('part_time_job')
plt.ylabel('physics_score')
plt.show()

df

df["extracurricular_activities"] = df["extracurricular_activities"].map({False: 0, True:1})

x = df[['absence_days','extracurricular_activities']].values.reshape(-1,2)
y = df['math_score']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df.head()

from sklearn import metrics
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))

import matplotlib.pyplot as plt


plt.figure(figsize=(5, 5), dpi=100)
plt.scatter(X_test[:, 0], y_test, color='black', marker='x', s=100, label='Actual')
plt.plot(X_test[:, 0], y_pred, color='red', linewidth=2, label='Regression Line')
plt.xlabel('Absence Days')
plt.ylabel('Math Score')
plt.legend()
plt.grid(False)
plt.box(False)
plt.show()